SELab-2/Dr-Trottoir-1

api/example.env, api/package-lock.json, api/package.json, api/src/main.ts, api/src/routes/mail.ts, api_query/src/index.ts, api_query/src/mail.ts
Er is een nieuwe route `Mail`, die enkel `POST` requests behandelt om een mail te sturen. De request body moet de volgende velden bevatten:
- `to`: het emailadres van de syndicus waar de mail naar gestuurd wordt
- `subject`: het onderwerp van de mail
- `content`: de inhoud van de mail
Deze nieuwe route zorgt ervoor dat superstudenten en admins een mail kunnen sturen naar een syndicus omtrent een gebouw.
Er zijn geen testen geschreven voor deze route. Ik denk dat we dat ook beter niet doen, omdat er anders elke keer een email gestuurd wordt bij het uitvoeren van de test.
=> API: nieuwe mail route

web/src/views/account/LoginScreen.vue
closes #379 
Men is nu in staat om in te loggen in de login pagina door op enter te duwen in het wachtwoord veld.
Het inloggen d.m.v. enter is een intiütieve actie, deze moest toegevoegd worden.
New feature (non-breaking wijziging met nieuwe functionaliteit)
=> Frontend: Login bevestigen met enter

api/__tests__/routes/user.test.ts, api/package-lock.json, api/package.json, api/src/routes/user.ts, api/src/validators/user.validator.ts
Voegt validatie toe aan de meegegeven wachtwoorden. Deze validatie wordt gedaan nog voor de request in onze API methodes binnenkomt, dankzij de [joi-password](https://github.com/Heaty566/joi-password) package.
Wij kunnen het niet toestaan dat een gebruiker een willekeurig wachtwoord gebruikt, het moet aan zekere eisen voldoen om de veiligheid van onze app te waarborgen. 
Elke eis is getest door afzonderlijke test.
Huidige wachtwoorden die wij gebruiken voldoen niet aan deze eisen. Voor het gemak, vooral tijdens demo, houden wij het zo.
=> API: Wachtwoord validatie

api/__tests__/utilities/parser.test.ts, api/src/parser.ts
Toevoeging van Parser tests.
Eenvoudige `parser.test.ts` test suite.
Enkele methodes in Parser zijn aangepast om de onbereikbare paden te verwijderen.
Methode `Parser.stringArray` is verwijderd, omdat deze niet gebruikt wordt in API.
=> API: Parser tests

Dockerfile, api/__tests__/mock/file.ts, api/__tests__/routes/progress.test.ts, api/src/main.ts, api/src/routes/building.ts, api/src/routes/file.ts, api/src/routes/progress.ts, api/src/validators/building.validator.ts, api/src/validators/progress.validator.ts, api_query/src/building.ts, api_query/src/file.ts, api_query/src/index.ts, api_query/src/progress.ts, docker-compose.dev.yml, docker-compose.yml, orm/prisma/schema.prisma, web/__tests__/env.ts, web/__tests__/imgproxy.test.ts, web/src/imgproxy.ts, web/src/router/index.ts, web/src/views/dev/ImageTest.vue, web/src/views/round/RoundDetail.vue
Een volledige implementatie van file uploaders en downloaders in de API en query builder, alsook een uitgebreide proof of concept in op de `/dev/image` pagina van de Vue applicatie.
De implementatie in de app zelf voorzie ik nog in een tweede PR die vertrekt vanaf deze.
- De ImgProxy configuratie is aangepast naar een enkelvoudige `IMGPROXY_SERVER_ADDRESS` variabele. De Dockerfile en compose files werden hiervoor aangepast.
- Er is een nieuwe `FileQuery` klasse. Deze maakt het mogelijk om de identifier van een `select` component door te geven en de file te uploaden. Het resultaat is een `File` object.
- De `Image` tabel werd vervangen door de `File` tabel, aangezien deze voornamelijk dezelfde functionaliteit hadden. Dit maakt het gebruik heel wat eenvoudiger. We laten ImgProxy nu …
=> Image download en upload support with ImgProxy

api/__tests__/routes/progress.test.ts, api/__tests__/routes/round.test.ts, api/__tests__/routes/round_building.test.ts, api/__tests__/routes/schedule.test.ts, api/__tests__/utilities/Testrunner.ts, api/src/routes/round.ts, api/src/validators/round.validator.ts, orm/prisma/schema.prisma
Zie #447. De optie `deleted` werd toegevoegd aan de schema van `Round`.
De test rond ronde verwijderen werd opgesplitst in een soft delete en een hard delete.
`GET /round` accepteert nu een `deleted` parameter.
`DELETE /round/:id` accepteert nu `hardDelete` in de body van de request.
=> API: soft deleting van ronde

web/src/components/cards/BuildingCard.vue, web/src/views/building/BuildingFollowup.vue
Deze PR implementeerd de api al voor de buildingfollowup. Heeft echter nog errors omdat deze branch is gestart van round-followup. Wordt daar in herwerkt.
=> feat: rework BuildingFollowup, now works with new api

web/src/components/popups/CardPopup.vue, web/src/views/account/AccountSettings.vue
Redesign van de pop bij account wijzigingen.
De stijl van de vorige implementatie zat helemaal niet oke, dus die is nu bijgestuurd.
=> Web: redesign van popup bij account wijziging

web/src/views/round/RoundMaker.vue
Bij het aanmaken van een ronde kon geen beschrijving gegeven worden. 
Zoals op de screenshots te zien is, wordt de beschrijving correct meegegeven.
=> Frontend: beschrijving bij aanmaken ronde

web/src/views/building/BuildingMaker.vue
Een gebruiker kan nu een handleiding selecteren bij het aanmaken van een gebouw. Deze wordt automatisch aangemaakt.
Manuele testen.
Closes #470.
=> Web: uploaden van handleiding bij aanmaken gebouw

web/src/layouts/MainLayout.vue, web/src/views/contact/TemplateBuilder.vue
Er was nog tekst dat template gebruikte ipv sjabloon, deze is nu gefixt.
Sluit #497.
Niets veranderd aan de UI.
=> Frontend: hernoeming template naar sjabloon

web/src/views/building/BuildingScreen.vue
- syndicus moet taken voor zijn eigen gebouw kunnen zien
- syndicus mag knop om naar zichzelf te bellen en mailen niet zien
issues oplossen
geen testen
Close #493 #492
=> Web: syndicus ziet taken

web/src/views/contact/ContactSyndicus.vue, web/src/views/dashboard/Template.vue
- superstudent kan templates maken
- de naam van de syndicus is toegevoegd aan het contactformulier
- op het einde van het contact formulier werd "met vriendelijke groeten Dr. Trottoir" toegevoegd.
issues
geen testen
close #489 #490
=> Web: super-student sjabloon maken

web/src/components/cards/UserAnalyticCard.vue
Analoog aan #513, maar voor de gebruikers zelf.
=> Web: integratie statistieken voor studenten

web/src/components/popups/StartRoundPopupContent.vue
Consistentie-update voor pop up bij starten ronde.
Idem aan vorige.
=> Web: round start popup redesign

web/src/components/cards/UserAnalyticCard.vue
=> Hotfix: remove unused wrong building querry in useranalytics

web/src/components/cards/BuildingCard.vue
Deze PR biedt een refactor van `BuildingCard` aan, en een lichte wijziging aan de layout.
Niet getest.
=> Web: refactor van Building Card

web/src/components/cards/BuildingCard.vue, web/src/views/contact/TemplateBuilder.vue
Momenteel kreeg je nog een bad request wanneer men geen input gaf in tekstvelden.
Sluit #525.
Geen testen nodig.
=> Frontend: input checks voor input

web/src/views/account/AccountSettings.vue
Het afsluiten van de bewerkmodus gebeurt nu uitsluitend wanneer de `PATCH` request succesvol was.
#520
Closes #520
=> Web: fix #520

api_query/src/file.ts
Het adres om bestanden te uploaden is niet langer hardgecodeerd.
Closes #530
Manueel getest.
=> Query: remove hard coded server address

web/src/views/building/BuildingScreen.vue
De handleiding wordt nu correct gelinkt.
Closes #499
Niet van toepassing
=> Web: fix #499

api/__tests__/routes/user.test.ts, api/src/routes/user.ts
Closes #491.
Er is een bug ingekropen waar student (en elk user in het algemeen) kon zijn eigen permissieniveau aanpassen.
Dit is nu opgelost
Er is een test suite voor deze issue geschreven
=> Bug: Sta enkel admin users toe om permissieniveau aan te passen

web/src/views/student/SchedulingScreenStudents.vue
Wanneer een ronde ingepland werd voor een student op een bepaald uur, kwam er in het overzicht van die student een verkeerd uur te staan.
=> fix: correct uur bij planning student
